services:
  postgres:
    image: "postgres:17"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./seeds/postgres:/docker-entrypoint-initdb.d
    networks:
      - app-network

  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"
    volumes:
      - ./compose-s3-init.sh:/etc/localstack/init/ready.d/init-s3.sh
    networks:
      - app-network

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bun dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      MY_ENCRYPTION_KEY: unicorn
      MY_POSTGRES_CONNECTION_URL: postgresql://postgres:postgres@postgres
      MY_S3_ACCESS_KEY: test
      MY_S3_SECRET_KEY: test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
